[project]
name = "Approximations"
version = "0.1.0"
description = "A code to evaluade the viability of various approximations to the Rmatrix function."

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]